<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class=""><?echo $course->name; ?></h1>
				<h3><?echo $course->description; ?></h3>
			</div>
		</div>
	</div>
</div>
<div class="py-2">
	<div class="container">
		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Главы</h2>
				<div class="list-group">
					<div class="list-group-item">

						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>Глава1</b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1" contenteditable="true">Описание</h6>
							<small>Оценка</small>
						</div>
						<div>
							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						<a class="btn btn-danger" href="#comment" style="width: 100%" data-toggle="collapse" role="button" aria-expanded="false"
						 aria-controls="comment">Комментарии</a>
						<div class="collapse multi-collapse" id="comment">
							<!-- <div class="card card-body">
								<h5>Комментатор, <span class="small text-mute">00:00</span> <span class="small text-secondary">студент</span></h5>
								<p>Комментарий</p>
							</div> -->
							<?  echo CustomTags::comment(
								[
									'username' => 'student@test',
									'time'   => '19:50',
									'usertype' => 'студент',
									'commenttext' => 'тестовый комментарий',
								]
							); ?>
							<div class="card card-body">
								<h5>Комментатор, <span class="small text-mute">00:00</span> <span class="small text-secondary">студент</span></h5>
								<p>Комментарий</p>
							</div>
							<div class="card card-body">
								<h5>Комментатор, <span class="small text-mute">00:00</span> <span class="small text-secondary">студент</span></h5>
								<p>Комментарий</p>
							</div>
							<div class="card card-footer">

								<form class="form-inline">
									<textarea class="form-control w-100" id="exampleTextarea" rows="3"></textarea>
								</form>
								<a href="#" class="btn btn-outline-primary" style="width: 100%">Отправить</a>
							</div>

						</div>

					</div>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>Глава2</b></h4>
							<small class="text-muted">3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1">Описание</h6>
							<small class="text-muted">Оценка</small>
						</div>
						<a class="btn btn-danger" href="#" style="width: 100%">Комментарии</a>
					</div>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Приложения</h2>
				<div class="list-group">
					<div class="list-group-item">

						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>Приложение 1</b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1" contenteditable="true">Описание</h6>
							<small>Оценка</small>
						</div>
						<div>
							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						<a class="btn btn-danger" href="#comment" style="width: 100%">Комментарии</a>
					</div>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>Приложение 1</b></h4>
							<small class="text-muted">3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1">Описание</h6>
							<small class="text-muted">Оценка</small>
						</div>
						<a class="btn btn-danger" href="#" style="width: 100%">Комментарии</a>
					</div>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Графические материалы</h2>
				<div class="list-group">
					<div class="list-group-item">

						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>Приложение 1</b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1" contenteditable="true">Описание</h6>
							<small>Оценка</small>
						</div>
						<div>
							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						<a class="btn btn-danger" href="#comment" style="width: 100%">Комментарии</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>