<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Поиск студентов
    </h1>

</div>
<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "student/search/".$course_id,
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSecondName" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFatherName" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["father_name", "size" => 30, "class" => "form-control", "id" => "fieldFatherName"]) ?>
    </div>
</div>



<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Звание (для преподователей)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
