<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
       echo \Phalcon\Tag::javascriptInclude("public/js/userform.js"); 
?>
<nav aria-label="breadcrumb" class='pt-3'>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["course/list", "Курсы"]); ?></li>
        <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["course/index/".$course_id, Course::findFirst($course_id)->name]); ?></li>
		<li class="breadcrumb-item active">Поиск студентов</li>
    </ol>
</nav>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#fieldGroupBlock').show();
        });
    </script>
   <div class="modal"  id="set_group">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Выбрать группу</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table id="groups" class="table table-bordered table-hover" >
                        <thead>
                            <tr>
                                <th>id</th>
                                <th>Название</th>
                                <th>Год</th>
                                <th>Форма обучения</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?
                            foreach ($groups as $key => $group) {
                                    echo 
                                    '<tr>'.
                                        '<td class="group_id">'.$group->group_id.'</td>'.
                                        '<td class="group_name">'.$group->name.'</td>'.
                                        '<td class="group_year">'.$group->year.'</td>'.
                                        '<td>'.$group->type.'</td>'.
                                    '</tr>';
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<div class="page-header">
    <h1>Поиск студентов</h1>
</div>
<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "student/search/".$course_id,
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSecondName" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFatherName" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["father_name", "size" => 30, "class" => "form-control", "id" => "fieldFatherName"]) ?>
    </div>
</div>


<div class="form-group" id="fieldGroupBlock">
    <label for="fieldGroupGroupId" class="col-sm-2 control-label">Группа (для студентов)</label>
    <div class="col-sm-10 input-group">
        <?php echo $this->tag->textField(["group_group_id", "type" => "number", "class" => "form-control", "id" => "fieldGroupGroupId","readonly" => "true"]) ?>
        <?php echo $this->tag->textField(["group_name", "class" => "form-control", "id" => "fieldGroupName","readonly" => "true"]) ?>
        <div class="input-group-append">
            <button class="btn-secondary" type="button" data-toggle="modal" data-target="#set_group">
                <i class="fas fa-search "></i>
            </button>
            <button class="btn-danger" type="button" id="erase_group">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
