-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 10:35:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema konlabu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema konlabu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `konlabu` DEFAULT CHARACTER SET utf8 ;
USE `konlabu` ;

-- -----------------------------------------------------
-- Table `konlabu`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL COMMENT 'email, baby',
  `pass` VARCHAR(60) NULL COMMENT 'pass, baby',
  `type` ENUM('admin', 'teach', 'student') NULL,
  `name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `father_name` VARCHAR(45) NULL,
  `group_group_id` INT NULL,
  `title` VARCHAR(127) NULL COMMENT 'Титул преподавателя.',
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_group_idx` (`group_group_id` ASC),
  CONSTRAINT `fk_user_group`
    FOREIGN KEY (`group_group_id`)
    REFERENCES `konlabu`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`subsection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`subsection` (
  `subsection_id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NULL,
  `grade` ENUM('ужасно', 'все плохо', 'уже лучше', 'как надо') NULL,
  `discription` VARCHAR(45) NULL,
  `section` ENUM('главы', 'приложения', 'графические материалы') NULL,
  `course_course_id` INT NOT NULL,
  PRIMARY KEY (`subsection_id`),
  INDEX `fk_subsection_course1_idx` (`course_course_id` ASC),
  CONSTRAINT `fk_subsection_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `konlabu`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`user_has_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`user_has_course` (
  `user_user_id` INT NOT NULL AUTO_INCREMENT,
  `course_course_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `course_course_id`),
  INDEX `fk_user_has_course_course1_idx` (`course_course_id` ASC),
  INDEX `fk_user_has_course_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_course_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `konlabu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_course_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `konlabu`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `datatime` DATETIME NULL,
  `text` VARCHAR(511) NULL,
  `subsection_subsection_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_subsection1_idx` (`subsection_subsection_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_comment_subsection1`
    FOREIGN KEY (`subsection_subsection_id`)
    REFERENCES `konlabu`.`subsection` (`subsection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `konlabu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konlabu`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konlabu`.`file` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NULL,
  `datetaime` DATETIME NULL,
  `subsection_subsection_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_file_subsection1_idx` (`subsection_subsection_id` ASC),
  CONSTRAINT `fk_file_subsection1`
    FOREIGN KEY (`subsection_subsection_id`)
    REFERENCES `konlabu`.`subsection` (`subsection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
