<div class="py-1">
	<div class="container">
		<div class="row pb-4">
			<div class="col-md-12">
				<h1 class="">Редактирование курса</h1>
				<?php echo $this->tag->form(["course/save","method" => 'POST']); ?>
				<p>
				<label for="name">Название курса</label><br/>
				<?php echo $this->tag->textField([ "name", 'value' => $course->name ]); ?> </p>
				<p>
				<label for="description">Описание</label><br/>
				<?php echo $this->tag->textArea([ "description", 'value' => $course->description ]); ?>
				<?php echo $this->tag->hiddenField(['course_id',"value" => $course->course_id]); ?> </p>
				<p>
				<?php echo $this->tag->submitButton(['Сохранить', "class" => "btn btn-secondary"]); ?>
				<?php echo $this->tag->linkTo(['course/delete/'.$course->course_id, 'Удалить курс', 'class' => 'btn btn-danger']) ?> </p>
				</form>
			</div>
		</div>
	</div>
</div>
<?php echo $this->getContent(); ?>
<div class="container">
	<div class="row pb-4">
		<div class="col-md-12">
			<h2 class="">Главы</h2>
			<?php echo $this->tag->form(["subsection/create","method" => 'POST']); ?>
			<p>
			<label for="theme"> Название главы </label><br/>
			<?php echo $this->tag->textField("theme"); ?> </p>
			<p>
			<label for="description">Описание</label><br/>
			<?php echo $this->tag->textArea("description"); ?> </p>

			<?php echo $this->tag->hiddenField(['section',"value" => 'главы']); ?>
			<?php echo $this->tag->hiddenField(['course_course_id',"value" => $course->course_id]); ?> 

			<?php echo $this->tag->submitButton(['Добавить раздел', "class" => "btn btn-secondary"]); ?> </p>
			</form>
			<div class="list-group">
					
<?
	if($chapters!=null){
		foreach ($chapters as $number => $subsection) {
			?>
			<div class="list-group-item">
				<?php echo $this->tag->form(["subsection/save","method" => 'POST']); ?>
				<div class=" w-100">
					<label for="theme"> Название главы </label><br/>
					<?php echo $this->tag->textField(["theme", 'value'=>$subsection->theme,]); ?>

				</div>
				<div class=" w-100">
					<label for="description">Описание</label><br/>
					<?php echo $this->tag->textArea(["description", 'value'=>$subsection->description, 'class'=>'w-100']); ?> 
					<?php echo $this->tag->hiddenField(['course_id',"value" => $course->course_id]); ?>
					<?php echo $this->tag->hiddenField(['subsection_id',"value" => $subsection->subsection_id]); ?>
				</div><br>
				<?php echo $this->tag->submitButton(['Сохранить изменения', "class" => "btn btn-secondary"]); ?>
				<?php echo $this->tag->linkTo(['subsection/delete/'.$subsection->subsection_id, 'Удалить раздел', 'class' => 'btn btn-danger']) ?>
				</form>				
			</div>
			<?
		}
	}?>
	</div>
	<h2 class="">Приложения</h2>
			<?php echo $this->tag->form(["subsection/create","method" => 'POST']); ?>
			<p>
			<label for="theme"> Название приложения </label><br/>
			<?php echo $this->tag->textField("theme"); ?> </p>
			<p>
			<label for="description">Описание</label><br/>
			<?php echo $this->tag->textArea("description"); ?> </p>

			<?php echo $this->tag->hiddenField(['section',"value" => 'приложения']); ?>
			<?php echo $this->tag->hiddenField(['course_course_id',"value" => $course->course_id]); ?> 

			<?php echo $this->tag->submitButton(['Добавить раздел', "class" => "btn btn-secondary"]); ?> </p>
			</form>
			<div class="list-group">
					
<?
	if($applications!=null){
		foreach ($applications as $number => $subsection) {
			?>
			<div class="list-group-item">
				<?php echo $this->tag->form(["subsection/save","method" => 'POST']); ?>
				<div class=" w-100">
					<label for="theme"> Название главы </label><br/>
					<?php echo $this->tag->textField(["theme", 'value'=>$subsection->theme,]); ?>

				</div>
				<div class=" w-100">
					<label for="description">Описание</label><br/>
					<?php echo $this->tag->textArea(["description", 'value'=>$subsection->description, 'class'=>'w-100']); ?> 
				</div><br>
				<?php echo $this->tag->hiddenField(['course_course_id',"value" => $course->course_id]); ?> 
				<?php echo $this->tag->hiddenField(['subsection_id',"value" => $course->course_id]); ?> 
				<?php echo $this->tag->submitButton(['Сохранить изменения', "class" => "btn btn-secondary"]); ?>
				<?php echo $this->tag->linkTo(['subsection/delete/'.$subsection->subsection_id, 'Удалить раздел', 'class' => 'btn btn-danger']) ?>
				</form>				
			</div>
			<?
		}
	}?>
	</div>
	<h2 class="">Графические материалы</h2>
			<?php echo $this->tag->form(["subsection/create","method" => 'POST']); ?>
			<p>
			<label for="theme"> Название графических материалов </label><br/>
			<?php echo $this->tag->textField("theme"); ?> </p>
			<p>
			<label for="description">Описание</label><br/>
			<?php echo $this->tag->textArea("description"); ?> </p>

			<?php echo $this->tag->hiddenField(['section',"value" => 'графические материалы']); ?>
			<?php echo $this->tag->hiddenField(['course_course_id',"value" => $course->course_id]); ?> 

			<?php echo $this->tag->submitButton(['Добавить раздел', "class" => "btn btn-secondary"]); ?> </p>
			</form>
			<div class="list-group">
					
<?
	if($charts!=null){
		foreach ($charts as $number => $subsection) {
			?>
			<div class="list-group-item">
				<?php echo $this->tag->form(["subsection/save","method" => 'POST']); ?>
				<div class=" w-100">
					<label for="theme"> Название главы </label><br/>
					<?php echo $this->tag->textField(["theme", 'value'=>$subsection->theme,]); ?>

				</div>
				<div class=" w-100">
					<label for="description">Описание</label><br/>
					<?php echo $this->tag->textArea(["description", 'value'=>$subsection->description, 'class'=>'w-100']); ?> 
				</div><br>
				<?php echo $this->tag->hiddenField(['course_course_id',"value" => $course->course_id]); ?> 
				<?php echo $this->tag->submitButton(['Сохранить изменения', "class" => "btn btn-secondary"]); ?>
				<?php echo $this->tag->linkTo(['subsection/delete/'.$subsection->subsection_id, 'Удалить раздел', 'class' => 'btn btn-danger']) ?>
				</form>				
			</div>
			<?
		}
	}?>		</div>
		</div>
	</div>
</div>