<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class=""><?echo $course->name; ?></h1>
				<h3><?echo $course->description; ?></h3>
				<a>
              <?
              
           echo $this->tag->linkTo( 
              [
                "course/edit/".$course->course_id,
                "Редактировать курс",
              	"class" => "btn btn-outline-primary",
            ]
            );
            echo $this->tag->linkTo( 
              [
                "student/search/".$course->course_id,
                "Подписать на курс",
              	"class" => "btn btn-outline-primary",
            ]
            );
?>
            </a>
			</div>
		</div>
	</div>
</div>

<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="">Список студентов</h1>
				 <?
              foreach ($page->items as $item) 
                { 
                  ?>
                  <a>
              <?
		           echo $this->tag->linkTo( 
		              [
		                "course/show/".$course->course_id."/".$item->user_id,
		                " <div class='d-flex w-100 justify-content-between'>
		                <h5 class='mb-1'>".$item->name."</h5>
		              </div>",
		              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",

		            ]
		            );
				?> 
				</a>
				<? } ?>
			</div>
		</div>
	</div>
</div>	