<div class="modal fade" id="createCourse">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Создать курс</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <?echo Phalcon\Tag::form(
            [
                "course/create",
                "method" => "post",
                "class"=>"form-horizontal",
            ]
        );?>
        <div class="form-group">
          <label for="nameInput">Наименование</label>
          <input type="text" name="name" class="form-control" id="nameInput">
        </div>
        <div class="form-group">
          <label for="descriptionInput">Описание</label>
          <textarea type="text" name="description" class="form-control" id="descriptionInput"></textarea>
        </div>
        <div class="form-group">
          <button type="submit" style="width:100%" class="btn btn-outline-secondary">Создать курс</button>
        </div>
        </form>
      </div>
    </div><!-- /.модальное окно-Содержание -->
  </div><!-- /.модальное окно-диалог -->
</div>
<!-- /.модальное окно -->
 <div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Курсы</h1>
        </div>
      </div>
    </div>
  </div>
  <?php echo $this->getContent(); ?>

          <?  
          $role=$this->session->auth['role'];
          if($role != 'guest' && $role != null) {
            if($role=='teach') {
              echo $this->tag->linkTo( 
                [
                  "",
                  "Добавить курс",
                  'class' => 'btn btn-secondary',
                  'data-toggle' => 'modal',
                  'data-target' => '#createCourse'
                ]
              );
            }
          }
          ?>

  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
           <?php 
              
              if($role != 'guest' && $role != null){
                if($role=='teach') {
                  foreach ($page->items as $item)
                  { 
            ?>
            <a>
            <?
            echo $this->tag->linkTo( 
              [
                "course/index/".$item->course_id,
                " <div class='d-flex w-100 justify-content-between'>
                <h5 class='mb-1'>".$item->name."</h5>
                <small>3 days ago</small>
              </div>
              <div class='d-flex w-100 justify-content-between'>
                <p class='mb-1'>".$item->description."</p>
                <small>Оценка</small>
              </div>",
              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",
            ]
            );
            ?>
            </a>
            <? } 
            } elseif($role=='student'){
              foreach ($page->items as $item)
                  { 
            ?>
            <a>
            <?
            echo $this->tag->linkTo( 
              [
                "course/show/".$item->course_id."/".$this->session->auth['id'],
                " <div class='d-flex w-100 justify-content-between'>
                <h5 class='mb-1'>".$item->name."</h5>
                <small>3 days ago</small>
              </div>
              <div class='d-flex w-100 justify-content-between'>
                <p class='mb-1'>".$item->description."</p>
                <small>Оценка</small>
              </div>",
              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",
            ]
            );
            ?>
            </a>
            <? }}} ?> 
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center pt-2">
      <?//пример использования пагинации
      echo CustomTags::pagination([
                      'link' => 'course/list?page=%d',
                      'current' => $page->current,
                      'next' => $page->next,
                      'before' => $page->before,
                      'count'   => $page->total_pages,
                  ]);
        ?>
    </div>
    </div>
  </div>