 <div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Курсы</h1>
        </div>
      </div>
    </div>
  </div>
  
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
           
              <?
              foreach ($page->items as $item) 
                { 
                  ?>
                  <a>
              <?
              
           echo $this->tag->linkTo( 
              [
                "subsection/index/".$item->course_id,
                " <div class='d-flex w-100 justify-content-between'>
                <h5 class='mb-1'>".$item->name."</h5>
                <small>3 days ago</small>
              </div>
              <div class='d-flex w-100 justify-content-between'>
                <p class='mb-1'>".$item->description."</p>
                <small>Оценка</small>
              </div>",
              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",

            ]
            );
?>
           
             
            </a>
            <? } ?>
            

          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center pt-2">
      <?//пример использования пагинации
      echo CustomTags::pagination([
                      'link' => 'course/list?page=%d',
                      'current' => $page->current,
                      'next' => $page->next,
                      'before' => $page->before,
                      'count'   => $page->total_pages,
                  ]);
        ?>
    </div>
    </div>
  </div>