<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class=""><?echo $course->name; ?></h1>
				<h3><?echo $course->description; ?></h3>
			</div>
		</div>
	</div>
</div>
<div class="py-2">
	<div class="container">
		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Главы</h2>
				<div class="list-group">
					<?foreach ($chapters as $number => $subsection) {?>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b><? echo $subsection->theme ?></b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1" contenteditable="true"><? echo $subsection->discription ?></h6>
							<small>Оценка</small>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
					        <form enctype="multipart/form-data" method="post">
							<p><input type="file" name="f">
							<input type="submit" value="Отправить"></p>
							</form>
							<?}}?>

							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						
						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%" data-toggle="collapse" role="button" aria-expanded="false"
						 aria-controls="comment">Комментарии</a>
						<div class="collapse multi-collapse" id="<? echo $subsection->subsection_id ?>">
							<? foreach ($subsection->getComment() as $comment) {
								$user = $comment->getUser();
								$username = $user->second_name.' '.mb_substr($user->name,0,1,"UTF-8").'.';
								if ($user->father_name) {
									$username .= ' '.mb_substr($user->father_name,0,1,"UTF-8").'.';
								}
								echo CustomTags::comment(
									[
										'username' => $username,
										'time'   => date('D, d/m/Y, H:i', strtotime($comment->datetime)),
										'usertype' => $user->type,
										'commenttext' => $comment->text,
									]
								);
							} ?>
							<div class="card card-footer">
								<?php echo $this->tag->form(["comment/create","method" => 'POST',"class" => 'form-inline']); ?>
									<?php echo $this->tag->textArea(["text","class" => 'w-100',"rows" => '3']); ?>
									<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
									<?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-outline-primary w-100"]); ?>
								</form>								
							</div>
						</div>
					</div>
					<?}?>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Приложения</h2>
				<div class="list-group">
					<?foreach ($applications as $number => $subsection) {?>
					<div class="list-group-item">

						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b><? echo $subsection->theme ?></b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1"><? echo $subsection->discription ?></h6>
							<small>Оценка</small>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
					        <form enctype="multipart/form-data" method="post">
							<p><input type="file" name="f">
							<input type="submit" value="Отправить"></p>
							</form>
							<?}}?>
							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%">Комментарии</a>
					</div>
				<?}?>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Графические материалы</h2>
				<div class="list-group">
				<? foreach ($charts as $number => $subsection) {?>
					<div class="list-group-item">

						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b><? echo $subsection->theme ?></b></h4>
							<small>3 days ago</small>
						</div>
						<div class="d-flex w-100 justify-content-between">
							<h6 class="mb-1" contenteditable="true"><? echo $subsection->discription ?></h6>
							<small>Оценка</small>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
					        <form enctype="multipart/form-data" method="post">
							<p><input type="file" name="f">
							<input type="submit" value="Отправить"></p>
							</form>
							<?}}?>
							<ul>
								<li>
									<a href="#" class="text-secondary">Файл 1</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 2</a>, 00:00, 00.00.00
								</li>
								<li>
									<a href="#" class="text-secondary">Файл 3</a>, 00:00, 00.00.00
								</li>
								<ul>
						</div>
						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%">Комментарии</a>
					</div>
					<?}?>
				</div>
			</div>
		</div>
	</div>
</div>