<? echo Phalcon\Tag::stylesheetLink("css/course_show.css"); ?>
<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center"><? echo $course->name; ?></h1>
				<h3><? echo $course->description; ?></h3>
			</div>
		</div>
	</div>
</div>
<?php echo $this->getContent(); ?>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link <? echo $tab_id == 'chapters' ? 'active show' : '' ?>" id="nav-chapters-tab" data-toggle="tab" href="#nav-chapters" role="tab" aria-controls="nav-chapters" aria-selected="<?echo $tab_id == 'chapters'?>"><h5>Главы</h5></a>
    <a class="nav-item nav-link <? echo $tab_id == 'applications' ? 'active show' : '' ?>" id="nav-applications-tab" data-toggle="tab" href="#nav-applications" role="tab" aria-controls="nav-applications" aria-selected="<?echo $tab_id == 'applications'?>"><h5>Приложения</h5></a>
    <a class="nav-item nav-link <? echo $tab_id == 'charts' ? 'active show' : '' ?>" id="nav-charts-tab" data-toggle="tab" href="#nav-charts" role="tab" aria-controls="nav-charts" aria-selected="<?echo $tab_id == 'charts'?>"><h5>Графический материал</h5></a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
	<div class="tab-pane fade <? echo $tab_id == 'chapters' ? 'active show' : '' ?>" id="nav-chapters" role="tabpanel" aria-labelledby="nav-chapters-tab">
		<div class="row mx-0">
			<div class="accordion col-12 p-0" id="accordionChapters">
				<?foreach ($chapters as $number => $subsection) {?>
					<?php $this->partial("course/show_partial", [ 'user' => $user, 'course' => $course, 'subsection' => $subsection, 'accordion_id' => 'accordionChapters', 'new_tab_id' => 'chapters' ]) ?>
				<?}?>
			</div>
		</div>
	</div>

	<div class="tab-pane fade <? echo $tab_id == 'applications' ? 'active show' : '' ?>" id="nav-applications" role="tabpanel" aria-labelledby="nav-applications-tab">
		<div class="row mx-0">
			<div class="accordion col-12 p-0" id="accordionApplications">
				<?foreach ($applications as $number => $subsection) {?>
					<?php $this->partial("course/show_partial", [ 'user' => $user, 'course' => $course, 'subsection' => $subsection, 'accordion_id' => 'accordionApplications', 'new_tab_id' => 'applications' ]) ?>
				<?}?>
			</div>
		</div>
	</div>

	<div class="tab-pane fade <? echo $tab_id == 'charts' ? 'active show' : '' ?>" id="nav-charts" role="tabpanel" aria-labelledby="nav-charts-tab">
		<div class="row mx-0">
			<div class="accordion col-12 p-0" id="accordionCharts">
				<?foreach ($charts as $number => $subsection) {?>
					<?php $this->partial("course/show_partial", [ 'user' => $user, 'course' => $course, 'subsection' => $subsection, 'accordion_id' => 'accordionCharts', 'new_tab_id' => 'charts' ]) ?>
				<?}?>
			</div>
		</div>
	</div>
</div>
<? echo Phalcon\Tag::javascriptInclude("js/course_show.js"); ?>