<div class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="">
					<?echo $course->name; ?>
				</h1>
				<h3>
					<?echo $course->description; ?>
				</h3>
			</div>
		</div>
	</div>
</div>
<?php echo $this->getContent(); ?>
<div class="py-2">
	<div class="container">
		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Главы</h2>
				<div class="list-group">
					<?foreach ($chapters as $number => $subsection) {?>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>
									<? echo $subsection->theme ?></b></h4>
							<small>
								<? if (count($subsection->getFile()) != 0) {
									$date = time(); 
									foreach ($subsection->getFile() as $file) { 
										if ($date > strtotime($file->datetime)) {
											$date = strtotime($file->datetime);
										}
									}
									echo date('d/m/Y, H:i', $date);
								} else {
									echo "Изменения отсутствуют";
								}
								?>
							</small>
						</div>
						<div class="d-flex w-100 justify-content-between my-1">
							<h5 class="mb-1" contenteditable="true">
								<? echo $subsection->discription ?>
							</h5>
							<div class="btn-group">
								<button type="button" class="btn btn-warning btn-sm"><? if ($subsection->grade != null) echo $subsection->grade; else echo "Оценка не выставлена"; ?></button>
								<? if ($this->session->auth['role'] == 'teach') {?>
								<button type="button" class="btn btn-warning btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<span class="sr-only">Toggle Dropdown</span>
								</button>
								<div class="dropdown-menu">
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/2', 'Ужасно', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/3', 'Все плохо', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/4', 'Уже лучше', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/5', 'Как надо', 'class' => 'dropdown-item']) ?>
								</div>
								<?}?>
							</div>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
							<?php echo $this->tag->form(["file/upload","method" => 'POST',"class" => 'form-inline py-1',"enctype"=>"multipart/form-data"]); ?>
							<div class="input-group">
								<input type="file" name="upFile" class="btn btn-outline-primary">
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<div class="input-group-append">
									<?php echo $this->tag->submitButton(['Загрузить', "class" => "btn btn-outline-primary", "name" => "upload"]); ?>
								</div>
							</div>
							</form>
							<?}}?>

							<div class="list-group">
								<? foreach ($subsection->getFile() as $file) { ?>
								<a href="<? echo '/file/download/'.$file->getUser()->user_id.'/'.$course->course_id.'/'.$subsection->subsection_id.'/'.$file->file_id ?>"
								 class="my-2 list-group-item list-group-item-action flex-column align-items-start">
									<div class="d-flex w-100 justify-content-between">
										<h6 class="mb-1">
											<? echo $file->filename ?>
										</h6>
										<small>
											<? echo date('d/m/Y, H:i', strtotime($file->datetime)) ?></small>
									</div>
								</a>
								<?}?>
							</div>
						</div>

						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%" data-toggle="collapse"
						 role="button" aria-expanded="false" aria-controls="comment">Комментарии</a>
						<div class="collapse multi-collapse" id="<? echo $subsection->subsection_id ?>" style="max-height: 50vh; overflow: scroll;">
							<? foreach ($subsection->getComment() as $comment) {
								$user = $comment->getUser();
								$username = $user->second_name.' '.mb_substr($user->name,0,1,"UTF-8").'.';
								if ($user->father_name) {
									$username .= ' '.mb_substr($user->father_name,0,1,"UTF-8").'.';
								}
								echo CustomTags::comment(
									[
										'username' => $username,
										'time'   => date('D, d/m/Y, H:i', strtotime($comment->datetime)),
										'usertype' => $user->type,
										'commenttext' => $comment->text,
									]
								);
							} ?>
							<div class="card card-footer">
								<?php echo $this->tag->form(["comment/create","method" => 'POST',"class" => 'form-inline']); ?>
								<?php echo $this->tag->textArea(["text","class" => 'w-100',"rows" => '3']); ?>
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-outline-primary w-100"]); ?>
								</form>
							</div>
						</div>
					</div>
					<?}?>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Приложения</h2>
				<div class="list-group">
					<?foreach ($applications as $number => $subsection) {?>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>
									<? echo $subsection->theme ?></b></h4>
							<small>
								<? if (count($subsection->getFile()) != 0) {
									$date = time(); 
									foreach ($subsection->getFile() as $file) { 
										if ($date > strtotime($file->datetime)) {
											$date = strtotime($file->datetime);
										}
									}
									echo date('d/m/Y, H:i', $date);
								} else {
									echo "Изменения отсутствуют";
								}
								?>
							</small>
						</div>
						<div class="d-flex w-100 justify-content-between my-1">
							<h5 class="mb-1" contenteditable="true">
								<? echo $subsection->discription ?>
							</h5>
							<div class="btn-group">
								<button type="button" class="btn btn-warning btn-sm"><? if ($subsection->grade != null) echo $subsection->grade; else echo "Оценка не выставлена"; ?></button>
								<? if ($this->session->auth['role'] == 'teach') {?>
								<button type="button" class="btn btn-warning btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<span class="sr-only">Toggle Dropdown</span>
								</button>
								<div class="dropdown-menu">
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/2', 'Ужасно', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/3', 'Все плохо', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/4', 'Уже лучше', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/5', 'Как надо', 'class' => 'dropdown-item']) ?>
								</div>
								<?}?>
							</div>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
							<?php echo $this->tag->form(["file/upload","method" => 'POST',"class" => 'form-inline py-1',"enctype"=>"multipart/form-data"]); ?>
							<div class="input-group">
								<input type="file" name="upFile" class="btn btn-outline-primary">
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<div class="input-group-append">
									<?php echo $this->tag->submitButton(['Загрузить', "class" => "btn btn-outline-primary", "name" => "upload"]); ?>
								</div>
							</div>
							</form>
							<?}}?>

							<div class="list-group">
								<?	foreach ($subsection->getFile() as $file) { ?>
								<a href="<? echo '/file/download/'.$file->getUser()->user_id.'/'.$course->course_id.'/'.$subsection->subsection_id.'/'.$file->file_id ?>"
								 class="my-2 list-group-item list-group-item-action flex-column align-items-start">
									<div class="d-flex w-100 justify-content-between">
										<h6 class="mb-1">
											<? echo $file->filename ?>
										</h6>
										<small>
											<? echo date('d/m/Y, H:i', strtotime($file->datetime)) ?></small>
									</div>
								</a>
								<?}?>
							</div>
						</div>

						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%" data-toggle="collapse"
						 role="button" aria-expanded="false" aria-controls="comment">Комментарии</a>
						<div class="collapse multi-collapse" id="<? echo $subsection->subsection_id ?>" style="max-height: 50vh; overflow: scroll;">
							<? foreach ($subsection->getComment() as $comment) {
								$user = $comment->getUser();
								$username = $user->second_name.' '.mb_substr($user->name,0,1,"UTF-8").'.';
								if ($user->father_name) {
									$username .= ' '.mb_substr($user->father_name,0,1,"UTF-8").'.';
								}
								echo CustomTags::comment(
									[
										'username' => $username,
										'time'   => date('D, d/m/Y, H:i', strtotime($comment->datetime)),
										'usertype' => $user->type,
										'commenttext' => $comment->text,
									]
								);
							} ?>
							<div class="card card-footer">
								<?php echo $this->tag->form(["comment/create","method" => 'POST',"class" => 'form-inline']); ?>
								<?php echo $this->tag->textArea(["text","class" => 'w-100',"rows" => '3']); ?>
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-outline-primary w-100"]); ?>
								</form>
							</div>
						</div>
					</div>
					<?}?>
				</div>
			</div>
		</div>

		<div class="row pb-4">
			<div class="col-md-12">
				<h2 class="">Графические материалы</h2>
				<div class="list-group">
					<?foreach ($charts as $number => $subsection) {?>
					<div class="list-group-item">
						<div class="d-flex w-100 justify-content-between">
							<h4 class="mb-1"><b>
									<? echo $subsection->theme ?></b></h4>
							<small>
								<? if (count($subsection->getFile()) != 0) {
									$date = time(); 
									foreach ($subsection->getFile() as $file) { 
										if ($date > strtotime($file->datetime)) {
											$date = strtotime($file->datetime);
										}
									}
									echo date('d/m/Y, H:i', $date);
								} else {
									echo "Изменения отсутствуют";
								}
								?>
							</small>
						</div>
						<div class="d-flex w-100 justify-content-between my-1">
							<h5 class="mb-1" contenteditable="true">
								<? echo $subsection->discription ?>
							</h5>
							<div class="btn-group">
								<button type="button" class="btn btn-warning btn-sm"><? if ($subsection->grade != null) echo $subsection->grade; else echo "Оценка не выставлена"; ?></button>
								<? if ($this->session->auth['role'] == 'teach') {?>
								<button type="button" class="btn btn-warning btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<span class="sr-only">Toggle Dropdown</span>
								</button>
								<div class="dropdown-menu">
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/2', 'Ужасно', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/3', 'Все плохо', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/4', 'Уже лучше', 'class' => 'dropdown-item']) ?>
									<? echo $this->tag->linkTo(['/subsection/grade/'.$course->course_id.'/'.$subsection->subsection_id.'/5', 'Как надо', 'class' => 'dropdown-item']) ?>
								</div>
								<?}?>
							</div>
						</div>
						<div>
							<?  
					        $role=$this->session->auth['role'];
					 		if($role != 'guest' && $role != null){
					            if($role=='student') {
					        ?>
							<?php echo $this->tag->form(["file/upload","method" => 'POST',"class" => 'form-inline py-1',"enctype"=>"multipart/form-data"]); ?>
							<div class="input-group">
								<input type="file" name="upFile" class="btn btn-outline-primary">
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<div class="input-group-append">
									<?php echo $this->tag->submitButton(['Загрузить', "class" => "btn btn-outline-primary", "name" => "upload"]); ?>
								</div>
							</div>
							</form>
							<?}}?>

							<div class="list-group">
								<?	foreach ($subsection->getFile() as $file) { ?>
								<a href="<? echo '/file/download/'.$file->getUser()->user_id.'/'.$course->course_id.'/'.$subsection->subsection_id.'/'.$file->file_id ?>"
								 class="my-2 list-group-item list-group-item-action flex-column align-items-start">
									<div class="d-flex w-100 justify-content-between">
										<h6 class="mb-1">
											<? echo $file->filename ?>
										</h6>
										<small>
											<? echo date('d/m/Y, H:i', strtotime($file->datetime)) ?></small>
									</div>
								</a>
								<?}?>
							</div>
						</div>

						<a class="btn btn-danger" href="#<? echo $subsection->subsection_id ?>" style="width: 100%" data-toggle="collapse"
						 role="button" aria-expanded="false" aria-controls="comment">Комментарии</a>
						<div class="collapse multi-collapse" id="<? echo $subsection->subsection_id ?>" style="max-height: 50vh; overflow: scroll;">
							<? foreach ($subsection->getComment() as $comment) {
								$user = $comment->getUser();
								$username = $user->second_name.' '.mb_substr($user->name,0,1,"UTF-8").'.';
								if ($user->father_name) {
									$username .= ' '.mb_substr($user->father_name,0,1,"UTF-8").'.';
								}
								echo CustomTags::comment(
									[
										'username' => $username,
										'time'   => date('D, d/m/Y, H:i', strtotime($comment->datetime)),
										'usertype' => $user->type,
										'commenttext' => $comment->text,
									]
								);
							} ?>
							<div class="card card-footer">
								<?php echo $this->tag->form(["comment/create","method" => 'POST',"class" => 'form-inline']); ?>
								<?php echo $this->tag->textArea(["text","class" => 'w-100',"rows" => '3']); ?>
								<?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
								<?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-outline-primary w-100"]); ?>
								</form>
							</div>
						</div>
					</div>
					<?}?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {
		$("textarea").val("")
	});
</script>