<div class="card">
    <div class="card-header" id="heading<?echo $subsection->subsection_id ?>">
        <button class="btn btn-link w-100" type="button" data-toggle="collapse" data-target="#collapse<?echo $subsection->subsection_id ?>" aria-expanded="false" aria-controls="collapse<?echo $subsection->subsection_id ?>">
            <div class="d-flex w-100 justify-content-between">
                <h4 class="mb-1"><b><?echo $subsection->theme ?></b></h4>
                <small>
                <?  if (count($subsection->getFile()) != 0) {
                        echo date('d/m/Y, H:i', strtotime($subsection->getFile(['order' => 'datetime DESC'])[0]->datetime));
                    } else {
                        echo "Изменения отсутствуют";
                    }
                    ?>
                </small>
            </div>
        </button>
        <div class="d-flex w-100 justify-content-between my-1">
            <p class="mb-1" contenteditable="true"> <?echo $subsection->description ?> </p>
            <div class="btn-group">
                <?  switch ($subsection->grade) {
                    case 'как надо':$alert_color = 'alert-success';
                        break;
                    case 'уже лучше':$alert_color = 'alert-primary';
                        break;
                    case 'все плохо':$alert_color = 'alert-warning';
                        break;
                    case 'ужасно':$alert_color = 'alert-danger';
                        break;
                    default:$alert_color = 'alert-dark';
                        break;
                }?>
                <div class="alert m-0 py-0 px-1 <?if ($this->session->auth['role'] == 'teach') { echo 'rounded-right-0 '; } echo $alert_color?>">
                <?  if ($subsection->grade != null) {
                        echo $subsection->grade;
                    } else {
                        echo "Оценка не выставлена";
                    }?>
                </div>
                <?if ($this->session->auth['role'] == 'teach') {?>
                <button type="button" class="btn btn-sm dropdown-toggle dropdown-toggle-split <?echo $alert_color ?>"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                    <?echo $this->tag->linkTo(['/subsection/grade/' . $course->course_id . '/' . $user->user_id . '/' . $new_tab_id . '/' . $subsection->subsection_id . '/2', 'Ужасно', 'class' => 'dropdown-item']) ?>
                    <?echo $this->tag->linkTo(['/subsection/grade/' . $course->course_id . '/' . $user->user_id . '/' . $new_tab_id . '/' . $subsection->subsection_id . '/3', 'Все плохо', 'class' => 'dropdown-item']) ?>
                    <?echo $this->tag->linkTo(['/subsection/grade/' . $course->course_id . '/' . $user->user_id . '/' . $new_tab_id . '/' . $subsection->subsection_id . '/4', 'Уже лучше', 'class' => 'dropdown-item']) ?>
                    <?echo $this->tag->linkTo(['/subsection/grade/' . $course->course_id . '/' . $user->user_id . '/' . $new_tab_id . '/' . $subsection->subsection_id . '/5', 'Как надо', 'class' => 'dropdown-item']) ?>
                </div>
                <?}?>
            </div>
        </div>
    </div>
    <div id="collapse<?echo $subsection->subsection_id ?>" class="collapse" aria-labelledby="heading<?echo $subsection->subsection_id ?>" data-parent="#<?echo $accordion_id?>">
        <div class="card-body">
            
            <div>
                <!-- Form Begin -->
                <?  $role = $this->session->auth['role'];
                    if ($role != 'guest' && $role != null) {
                        if ($role == 'student') { ?>
                <?php echo $this->tag->form(["file/upload", "method" => 'POST', "class" => 'form-inline py-1', "enctype" => "multipart/form-data"]); ?>
                <div class="input-group">
                    <input type="file" name="upFile" class="btn btn-outline-primary">
                    <?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
                    <div class="input-group-append">
                        <?php echo $this->tag->submitButton(['Загрузить', "class" => "btn btn-outline-primary", "name" => "upload"]); ?>
                    </div>
                </div>
                </form>
                <?}}?>
                <!-- Form End -->
                <div class="list-group" style="max-height: 30vh; overflow: auto;">
                    <!-- Файлы -->
                    <?  foreach ($subsection->getFile(['order' => 'datetime DESC']) as $file) {
                            echo $this->tag->linkTo([
                                "file/download/" . $file->getUser()->user_id . '/' . $course->course_id . '/' . $subsection->subsection_id . '/' . $file->file_id,
                                "<div class='d-flex w-100 justify-content-between'><h6 class='mb-1'>" . $file->filename . "</h6><small>" . date('d/m/Y, H:i', strtotime($file->datetime)) . "</small></div>",
                                "class" => "my-2 list-group-item list-group-item-action flex-column align-items-start",
                            ]);
                        }
                    ?>
                </div>
            </div>
            <a class="btn btn-danger" href="#<?echo $subsection->subsection_id ?>" style="width: 100%" data-toggle="collapse"
                role="button" aria-expanded="false" aria-controls="comment">Комментарии</a>
            <div class="collapse multi-collapse" id="<?echo $subsection->subsection_id ?>" style="max-height: 50vh; overflow: auto;">
                <?  foreach ($subsection->getComment() as $comment) {
                        $user = $comment->getUser();
                        $username = $user->second_name . ' ' . mb_substr($user->name, 0, 1, "UTF-8") . '.';
                        if ($user->father_name) {
                            $username .= ' ' . mb_substr($user->father_name, 0, 1, "UTF-8") . '.';
                        }
                        echo CustomTags::comment(
                            [
                                'username' => $username,
                                'time' => date('D, d/m/Y, H:i', strtotime($comment->datetime)),
                                'usertype' => $user->type,
                                'commenttext' => $comment->text,
                            ]
                        );
                    }
                ?>
                <div class="card card-footer">
                    <?php echo $this->tag->form(["comment/create", "method" => 'POST', "class" => 'form-inline']); ?>
                    <?php echo $this->tag->textArea(["text", "class" => 'w-100', "rows" => '3']); ?>
                    <?php echo $this->tag->hiddenField(['course_id', "value" => $course->course_id]); ?>
                    <?php echo $this->tag->hiddenField(['subsection_id', "value" => $subsection->subsection_id]); ?>
                    <?php echo $this->tag->hiddenField(['tab_id', "value" => $new_tab_id]); ?>
                    <?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-outline-primary w-100"]); ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>