<h1>Добро пожаловать!!!!</h1>
<br/>
<!-- <?
// echo Phalcon\Tag::linkTo(
//     [
//         "/session/logout",
//         "logout",
//         "class" => "btn-primary",
//     ]
// );
?> -->
<br/>
<?
echo 'Роль: '.$this->session->get('auth')['role'].'<br/>';
echo 'Почта: '.$this->session->get('auth')['email'].'<br/>';
echo PHP_EOL;
echo PHP_EOL;
echo $this->tag->linkTo( 
	"course",
	"Зарегистрировать курс!"
);
?>
<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Курсы</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
           
              <?
              foreach ($page->items as $item) 
                { 
              
           echo $this->tag->linkTo( 
              "subsection/index/".$item->couse_id,
              "Зарегистрировать курс!"
            );
?>
           <a href="" class="list-group-item list-group-item-action flex-column align-items-start btn-outline-primary">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><? echo $item->name; ?></h5>
                <small>3 days ago</small>
              </div>
              <div class="d-flex w-100 justify-content-between">
                <p class="mb-1"><? echo $item->description; ?></p>
                <small>Оценка</small>
              </div>
            </a>
            <? } ?>
            <a href="/robots/search">Первая</a> <a href="/robots/search?page=<?= $page->before; ?>">Предыдущая</a> <a href="/robots/search?page=<?= $page->next; ?>">Следующая</a> <a href="/robots/search?page=<?= $page->last; ?>">Последняя</a>
            <?php echo "Вы на странице ", $page->current, " из ", $page->total_pages; ?>
            <!-- 
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Курс 2</h5>
                <small class="text-muted">3 days ago</small>
              </div>
              <div class="d-flex w-100 justify-content-between">
                <p class="mb-1">Описание курса</p>
                <small>Оценка</small>
              </div>
            </a>
            <table border="1">
              <tr>
                <th>Имя</th>
                <th>Описание</th>
              </tr>
              <?
             // foreach ($page->items as $item) 
              //  { 
              ?>
              <tr>
                <td><? //echo $item->name; ?></td>
                <td><?// echo $item->description; ?></td>
              </tr>
              <?// } ?>
            </table>-->

          </div>
        </div>
      </div>
    </div>
  </div>
