<h1>Добро пожаловать!!!!</h1>
<br/>
<?
echo Phalcon\Tag::linkTo(
    [
        "/session/logout",
        "logout",
        "class" => "btn-primary",
    ]
);
?>
<br/>
<?
echo 'Роль: '.$this->session->get('auth')['role'].'<br/>';
echo 'email: '.$this->session->get('auth')['email'].'<br/>';
echo PHP_EOL;
echo PHP_EOL;
echo $this->tag->linkTo( 
	"course",
	"Зарегистрировать курс!"
);
?>
<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Курсы</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Курс 1</h5>
                <small>3 days ago</small>
              </div>
              <p class="mb-1">Описание курса</p>
            </a>
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Курс 2</h5>
                <small class="text-muted">3 days ago</small>
              </div>
              <p class="mb-1">Описание курса</p>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
