<h1>Добро пожаловать!!!!</h1>
<br/>
<!-- <?
// echo Phalcon\Tag::linkTo(
//     [
//         "/session/logout",
//         "logout",
//         "class" => "btn-primary",
//     ]
// );
?> -->
<br/>
<?
echo 'id: '.$this->session->get('auth')['id'].'<br/>';
echo 'Роль: '.$this->session->get('auth')['role'].'<br/>';
echo 'Почта: '.$this->session->get('auth')['email'].'<br/>';
echo PHP_EOL;
echo PHP_EOL;
echo $this->tag->linkTo( 
	"course",
	"Зарегистрировать курс!"
);
?>

