<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#groups').DataTable();
    $('#groups tbody tr').click(function(){
        var group_id = $(this).find(".group_id").text();
        var name = $(this).find(".group_name").text();
        $('#groups tr').removeClass("bg-secondary");
        $(this).addClass("bg-secondary");
        $('#fieldGroupGroupId').val(group_id);
        $('#fieldGroupName').val(name);

    });
} );
</script>

<style>
    tbody tr{
        cursor: pointer;
    }
</style>

<div class="modal"  id="set_group">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Выбрать группу</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table id="groups" class="table table-bordered table-hover" >
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?
                        foreach ($groups as $key => $group) {
                            echo 
                            '<tr>'.
                                '<td class="group_id">'.$group->group_id.'</td>'.
                                '<td class="group_name">'.$group->name.'</td>'.
                            '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<nav aria-label="breadcrumb" class='pt-3'>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["user/index", "Пользователи"]); ?></li>
    <li class="breadcrumb-item active">Создать пользователя</li>
  </ol>
</nav>

<div class="page-header">
    <h1>
        Create user
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>


<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPass" class="col-sm-2 control-label">Пароль</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["pass", "size" => 30, "class" => "form-control", "id" => "fieldPass"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Тип пользователя</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["type",  ['admin'=>'admin','teach'=>'teach','student'=>'student'], "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSecondName" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFatherName" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["father_name", "size" => 30, "class" => "form-control", "id" => "fieldFatherName"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldGroupGroupId" class="col-sm-2 control-label">Граппа(для студентов)</label>
    <div class="col-sm-10 input-group">
        <?php echo $this->tag->textField(["group_group_id", "type" => "number", "class" => "form-control", "id" => "fieldGroupGroupId","readonly" => "true"]) ?>
        <?php echo $this->tag->textField(["", "class" => "form-control", "id" => "fieldGroupName","readonly" => "true"]) ?>
        <div class="input-group-append">
            <button class="btn-secondary" type="button" data-toggle="modal" data-target="#set_group">
                <i class="fas fa-search "></i>
            </button>
        </div>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Звание (для преподователей)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>




