<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>



<nav aria-label="breadcrumb " class='pt-3'>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["user/index", "Пользователи"]); ?></li>
    <li class="breadcrumb-item active">Результаты поиска</li>
  </ol>
</nav>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>User</th>
            <th>Email</th>
            <th>Тип пользователя</th>
            <th>Даниил</th>
            <th>Отчество</th>
            <th>Фамилия</th>
            <th>Группа</th>
            <th>Title</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->user_id ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->type ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->second_name ?></td>
            <td><?php echo $user->father_name ?></td>
            <td><?php echo $user->group!=null ? $user->group->name:""; ?></td>
            <td><?php echo $user->title ?></td>

                <td><?php echo $this->tag->linkTo(["user/edit/" . $user->user_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->user_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="d-flex justify-content-center">
    <?//пример использования пагинации
        echo CustomTags::pagination([
                        'link' => 'user/search?page=%d',
                        'current' => $page->current,
                        'next' => $page->next,
                        'before' => $page->before,
                        'count'   => $page->total_pages,
                    ]);

    ?>
</div>
