<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<nav aria-label="breadcrumb" class='pt-3'>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["group", "Группы"]); ?></li>
    <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["group/search", "Результаты поиска"]); ?></li>
    <li class="breadcrumb-item active">Редактировать группу</li>
  </ol>
</nav>

<div class="page-header">
    <h1>
        Редактировать группу
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "group/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название группы</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">Год создания</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["year", "size" => 30, "class" => "form-control", "id" => "fieldYear"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Форма обучения</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["type", [], "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
