<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<nav aria-label="breadcrumb" class='pt-3'>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?php echo $this->tag->linkTo(["group", "Группы"]); ?></li>
    <li class="breadcrumb-item active">Результаты поиска</li>
  </ol>
</nav>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Group</th>
            <th>Name</th>
            <th>Year</th>
            <th>Type</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $group): ?>
            <tr>
                <td><?php echo $group->group_id ?></td>
            <td><?php echo $group->name ?></td>
            <td><?php echo $group->year ?></td>
            <td><?php echo $group->type ?></td>

                <td><?php echo $this->tag->linkTo(["group/edit/" . $group->group_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["group/delete/" . $group->group_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    <?//пример использования пагинации
        echo CustomTags::pagination([
                        'link' => 'group/search?page=%d',
                        'current' => $page->current,
                        'next' => $page->next,
                        'before' => $page->before,
                        'count'   => $page->total_pages,
                    ]);

    ?>
</div>