<!DOCTYPE html>
<html>
    <head>
        <? echo Phalcon\Tag::stylesheetLink("css/theme.css"); ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Вход</title>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!--выводим навбар, только для залогиненных.-->

        
            <nav class="navbar navbar-expand-md bg-primary navbar-dark bg-gradient">
                <div class="container">
                    <?
                      echo Phalcon\Tag::linkTo(
                          [
                              "/",
                              '<i class="fa d-inline fa-lg fa-cloud"></i><b> ВПИ/ВИТ</b>',
                              "class" => "navbar-brand",
                          ]
                      );
                    ?>
                  <?php 
                  $role=$this->session->auth['role'];
                  if($role != 'guest' && $role != null){
                   ?>
                    <? if($role!='admin') {?>
                      <!--для всех, кроме админа-->
                      <ul class="navbar-nav">
                        <li class="nav-item active">
                          <?
                            echo Phalcon\Tag::linkTo(
                                [
                                    "course/list",
                                    '<i class="fas fa-brain"></i> Курсы',
                                    "class" => "btn navbar-btn ml-2 text-light",
                                ]
                            );
                          ?>
                        </li>
                      </ul>
                      <ul class="navbar-nav">
                        <li class="nav-item active">
                          <?
                            echo Phalcon\Tag::linkTo(
                                [
                                    "user/edit",
                                    '<i class="fas fa-cog"></i> Настройки',
                                    "class" => "btn navbar-btn ml-2 text-light",
                                ]
                            );
                          ?>
                        </li>
                      </ul>
                    <? }?>

                    <? if($role=='admin') {?>
                      <!--только для администратора-->
                      <ul class="navbar-nav">
                        <li class="nav-item active">
                          <?
                            echo Phalcon\Tag::linkTo(
                                [
                                    "/user/",
                                    '<i class="fas fa-user"></i> Пользователи',
                                    "class" => "btn navbar-btn ml-2 text-light",
                                ]
                            );
                          ?>
                        </li>
                        <li class="nav-item active">
                          <?
                            echo Phalcon\Tag::linkTo(
                                [
                                    "/group/",
                                    '<i class="fas fa-users"></i> Группы',
                                    "class" => "btn navbar-btn ml-2 text-light",
                                ]
                            );
                          ?>
                        </li>
                      </ul>
                    <? }?>

                  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
                    <span class="navbar-text text-light"><? echo $this->session->get('auth')['email'] ?></span>
                      <?
                        echo Phalcon\Tag::linkTo(
                            [
                                "/session/logout",
                                "Выйти",
                                "class" => "btn navbar-btn ml-2 text-white btn-dark",
                            ]
                        );
                      ?>
                  </div>
                  <?php }else{?>
                        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
                          <a class="btn navbar-btn ml-2 text-white btn-dark" data-toggle="modal" data-target="#signIn">
                            <i class="fas fa-user"></i> Войти</a>
                        </div>
                    <?php } ?>
                </div>
              </nav>
        
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

    </body>
</html>
